#
# Local shim to make common targets (especially `clean`) work even when the
# autogenerated `Makefile` points at a kernel source directory that isn't
# present on this machine.
#

include Makefile

# Prevent GNU make from trying to rebuild the current Makefile by running
# `./configure` implicitly (e.g. under `make -B`). Regenerate explicitly with:
#   make reconfigure
Makefile:
	@:

# Regenerate `Makefile` explicitly.
reconfigure:
	./configure ${CARGS}
.PHONY: reconfigure

# If the configured kernel tree doesn't exist, fall back to the currently
# running kernel's build directory (typical for distro "linux-headers" packages).
ifeq ($(wildcard $(KDIR)/Makefile),)
KDIR := /lib/modules/$(shell uname -r)/build
KVERSION := $(shell uname -r)
endif

# Don't fail `make clean` when the kernel tree is missing; still remove local
# artifacts via `lclean`/`clean` from the included Makefile.
mclean:
	@if [ -d "$(KDIR)" ]; then \
		$(MAKE) -C "$(KDIR)" M="$(CURDIR)" clean; \
	else \
		echo " * Skipping kernel clean (KDIR=$(KDIR) not found)"; \
	fi
